### ISSUE TITLE
Doc error: recent_commit is now should_run

### ISSUE THREAD

**Issue by nealeu** [green-coding-berlin/green-ci-branch-activity-checker#4]
Looking at the debug when my attempt failed to run, it seems that `recent_commit` should now be `should_run` [here](https://github.com/green-coding-berlin/eco-ci-activity-checker/blame/main/README.md#L26)

Making this change worked for me.

It's a shame to have lost the "since x days ago" feature though, as that was right for me on our scheduled run, but that just means we can ensure that has it's own workflow which we should have done a while ago.

**Comment by ArneTR** [comment]
@dan-mm Can you have a look into it if that is a stale Readme?

**Comment by dan-mm** [comment]
Thank you for pointing this out! I've updated the readme accordingly :-)

**Comment by nealeu** [comment]
Thanks. And thanks for helping us reduce our carbon footprint. People so often think that "it's green electricity I'm using so it doesn't matter", but often don't understand that every kWh we avoid using is a reduction in coal and gas that's burned.
